export const iconNames: string[] = [
  "ic:round-directions-run",
  "mdi:meditation",
  "fluent:hat-graduation-12-filled",
  "fluent:dumbbell-20-filled",
  "ic:round-sports-gymnastics",
  "fa-solid:dollar-sign",
  "fe:cutlery",
  "medical-icon:i-no-smoking",
  "fa6-solid:shower",
  "fa6-solid:dog",
  "bi:book",
  "bxs:book",
  "bx:cycling",
  "mdi:cup-water",
  "icon-park-solid:sleep",
  "bi:tree-fill",
  "icon-park-solid:brain",
  "fa:bed",
  "fa6-solid:hands-holding-circle",
  "fa-solid:smile",
  "material-symbols:no-drinks-sharp",
  "fluent:food-apple-20-filled",
  "carbon:health-cross",
  "fa-solid:bath",
  "material-symbols:wifi-off-rounded",
];

export const iconColors: string[] = [
  "#f25555",
  "#55f27a",
  "#5594f2",
  "#f2ed55",
  "#f2a655",
  "#ae55f2",
  "#f27ecf",
  "#8a542b",
];
